### Get all todos

GET http://localhost:3000/api/v1/todos
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE3LCJleHAiOjE2OTczMTA4NDZ9.m9lbPucjDEbGbneODJRWTXhcrgncC-2AZ0ti_b5Qu8M

### Get todo by id

GET http://localhost:3000/api/v1/todos/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE3LCJleHAiOjE2OTczMTA4NDZ9.m9lbPucjDEbGbneODJRWTXhcrgncC-2AZ0ti_b5Qu8M

### Create new todo

POST http://localhost:3000/api/v1/todos
Content-Type: application/json

{
  "email": "daniel@test.local",
  "password": "secret12"
}